### ISSUE TITLE
Annotated data

### ISSUE THREAD

**Issue by jestlin15** [ltkagohara/HCC_cabonivo_visium#1]
Hi , Thank you so much for uploading the codes for your paper. I would love to use your results to perform further analysis for my research. May I please ask if it is able to obtain the process and annotated seurat object or the metadata generated from this paper please? Your help will be greatly appreciated!

**Comment by ltkagohara** [comment]
You can download the data from our GEO repository (https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE238264) and run the analysis for cell type annotations following our code.
